from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_copy_image_in_corresponding_folder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy_image_in_corresponding_folder.setStyleSheet("font: 75 10pt MS Shell Dlg 2;")
        self.btn_copy_image_in_corresponding_folder.setObjectName("btnOpenImage")
        self.horizontalLayout.addWidget(self.btn_copy_image_in_corresponding_folder)
        self.btn_recognize_image = QtWidgets.QPushButton(self.centralwidget)
        self.btn_recognize_image.setStyleSheet("font: 75 10pt MS Shell Dlg 2;")
        self.btn_recognize_image.setObjectName("btnRecognizeImage")
        self.horizontalLayout.addWidget(self.btn_recognize_image)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 26))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_image = QtWidgets.QAction(MainWindow)
        self.action_open_image.setObjectName("actionopen_image")
        self.action_save_image_as = QtWidgets.QAction(MainWindow)
        self.action_save_image_as.setObjectName("actionsave_image_as")
        self.menumenu.addAction(self.action_open_image)
        self.menumenu.addAction(self.action_save_image_as)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "recognition app"))
        self.btn_copy_image_in_corresponding_folder.setText(_translate("MainWindow", "copy image in corresponding folder"))
        self.btn_recognize_image.setText(_translate("MainWindow", "recognize image"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.action_open_image.setText(_translate("MainWindow", "open image"))
        self.action_save_image_as.setText(_translate("MainWindow", "save image as"))
